name: DB compatibility testing

on: [push, pull_request]

permissions:
  contents: read

jobs:
  valkey:
    name: Valkey ${{ matrix.valkey-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - valkey-version: '8.1.2'
          - valkey-version: '8.0.3'
          - valkey-version: '7.2.9'
    steps:
      - name: Prepare
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1.5.3
        with:
          packages: libevent-dev
          version: 1.0
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Create build folder
        run: cmake -E make_directory build
      - name: Generate makefiles
        shell: bash
        working-directory: build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DENABLE_IPV6_TESTS=ON -DTEST_WITH_VALKEY_VERSION=${{ matrix.valkey-version }} ..
      - name: Build
        shell: bash
        working-directory: build
        run: VERBOSE=1 make
      - name: Setup clusters
        shell: bash
        working-directory: build
        run: make start
      - name: Wait for clusters to start..
        uses: kibertoad/wait-action@99f6f101c5be7b88bb9b41c0d3b810722491b8e5 # 1.0.1
        with:
          time: '40s'
      - name: Run tests
        shell: bash
        working-directory: build
        run: make CTEST_OUTPUT_ON_FAILURE=1 test
      - name: Teardown clusters
        working-directory: build
        shell: bash
        run: make stop

  redis-comp:
    name: Redis ${{ matrix.redis-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - redis-version: '7.2.4'
          - redis-version: '7.0.15'
          - redis-version: '6.2.14'
    steps:
      - name: Prepare
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1.5.3
        with:
          packages: libevent-dev
          version: 1.0

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Create build folder
        run: cmake -E make_directory build

      - name: Generate makefiles
        shell: bash
        working-directory: build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DENABLE_IPV6_TESTS=ON -DTEST_WITH_REDIS_VERSION=${{ matrix.redis-version }} ..

      - name: Build
        shell: bash
        working-directory: build
        run: VERBOSE=1 make

      - name: Setup clusters
        shell: bash
        working-directory: build
        run: make start

      - name: Wait for clusters to start..
        uses: kibertoad/wait-action@99f6f101c5be7b88bb9b41c0d3b810722491b8e5 # 1.0.1
        with:
          time: '40s'

      - name: Run tests
        shell: bash
        working-directory: build
        run: make CTEST_OUTPUT_ON_FAILURE=1 test

      - name: Teardown clusters
        working-directory: build
        shell: bash
        run: make stop
